# Generated by Django 4.1.3 on 2023-04-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jwt_auth", "0002_subscription_userprofile_subscription_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_google_oauth",
            field=models.BooleanField(default=False),
        ),
    ]
