# Generated by Django 4.1.3 on 2023-06-22 06:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0003_userprofile_is_google_oauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Firstname must contain Alphabets only.', regex='^[a-zA-Z]+$')])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Lastname must contain Alphabets only.', regex='^[a-zA-Z]+$')])),
                ('email', models.EmailField(db_index=True, error_messages={'unique': 'User is already exist with given email address'}, max_length=254, unique=True, verbose_name='Email Address')),
            ],
        ),
    ]
