# Generated by Django 4.1.3 on 2023-06-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0004_waitinglist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitinglist',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
