# Generated by Django 4.1.3 on 2023-06-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0005_alter_waitinglist_email_alter_waitinglist_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitinglist',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
