# Generated by Django 4.1.3 on 2023-06-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0006_alter_waitinglist_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitinglist',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
